### ISSUE TITLE
"The issue of 'folder not found' occurs when running the program."

### ISSUE THREAD

**Issue by tsoul1** [lReDragol/OnceHuman_PhotoChanger#1]
"The issue of 'folder not found' occurs when running the program."
<img width="414" alt="v0 2 Once Human Photo Changer_cBAJPIguRj" src="https://github.com/user-attachments/assets/8a2ade2f-03c9-4d92-8bcf-8ffdc0599f90">

**Comment by tsoul1** [comment]
platfrom : steam  / os:win11 / language : kor

"It would be helpful to have a feature that allows the user to specify the folder when this issue occurs."

thx

**Comment by noxnoire** [comment]
Missing two / after The :  after The drive letter otherwise works as intended after fixing that bit also add The default library from The steam install you can get The location from windows registry
As a resume , add a way to find the default library and fix the issue where it checks for a path at C:steamlibrary/common/once human/
After C: its lacking two // but might be only one in case you had one

**Comment by lReDragol** [comment]
> "The issue of 'folder not found' occurs when running the program." <img alt="v0 2 Once Human Photo Changer_cBAJPIguRj" width="414" src="https://private-user-images.githubusercontent.com/178447183/358083174-8a2ade2f-03c9-4d92-8bcf-8ffdc0599f90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MTEzMDUsIm5iZiI6MTcyNDcxMTAwNSwicGF0aCI6Ii8xNzg0NDcxODMvMzU4MDgzMTc0LThhMmFkZTJmLTAzYzktNGQ5Mi04YmNmLThmZmRjMDU5OWY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQyMjIzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWQwNTcxODUxYzg4ZmJmY2Y5YjExOTdiZGNjNGJjYmFhNjM4NDAzNjU1NjU4MjdhZjUxNGYzYzUxNzI2NzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.35nngHjaOjHxdsGNJP5wblndzv2J0CzBna6FqM7fBrc">

Thank you for the error message.
This error has been fixed in the new program version V0.3.
If everything works or does not work for you, feel free to write your comments and I will try to fix these errors as soon as possible.

**Comment by lReDragol** [comment]
> platfrom : steam / os:win11 / language : kor
> 
> "It would be helpful to have a feature that allows the user to specify the folder when this issue occurs."
> 
> thx

Thanks for reporting this flaw!!!
I've already released the fixed version so you can try it out.
If everything will work and you have any ideas for extending the functionality, feel free to write and I will try to add or fix it.

**Comment by lReDragol** [comment]
> Missing two / after The : after The drive letter otherwise works as intended after fixing that bit also add The default library from The steam install you can get The location from windows registry As a resume , add a way to find the default library and fix the issue where it checks for a path at C:steamlibrary/common/once human/ After C: its lacking two // but might be only one in case you had one

Thank you for your comment.
But that wasn't the mistake.
I have already released a new version that you can test and tell me if it works for you or not.

**Comment by tsoul1** [comment]
thx 

issue fixed

"It would be helpful to include additional instructions on where to specify the path in the description."
